# Generated by Django 4.2.7 on 2024-03-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_user_name_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
    ]
