# Generated by Django 4.2.7 on 2024-03-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_animal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='parent',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
