# Generated by Django 5.0.3 on 2024-03-20 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_animal_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='deceased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, null=True)),
                ('number', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(null=True)),
                ('removed', models.DateField(auto_now=True, null=True)),
                ('cause', models.CharField(max_length=350, null=True)),
                ('image', models.ImageField(default='default.jpg', null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, null=True)),
                ('number', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(null=True)),
                ('sold_to', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(default='default.jpg', null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
